artifact_dir: artifacts/gpr_random
model_dir: models/gpr_random
train_data_path: data/processed/norm_train.csv
val_data_path: data/processed/norm_val.csv
n_start_points: 10
n_query: 100
estimation_step: 1
query_strategy_type: random
model_type: ActiveLearner
model_name: GaussianProcessRegressor
