artifact_dir: artifacts/gpr_gsy
model_dir: models/gpr_gsy
train_data_path: data/processed/norm_train.csv
val_data_path: data/processed/norm_val.csv
n_start_points: 10
n_query: 100
estimation_step: 1
query_strategy_type: gs_y
model_type: ActiveLearner
model_name: GaussianProcessRegressor
